---
--- Generated by Luanalysis
--- Created by THUNDER.
--- DateTime: 2020/11/27 14:22
---

local function http_post_client(url,project)
    local httpc = zhttp.new()
    timeout = 30000
    httpc:set_timeout(timeout)

    local res, err_ = httpc:request_uri(url, {
        method = "POST",
        body = {["errmsg"] = "sentry 熔断",["project"] = project},
        headers = {
            ["Content-Type"] = "application/json",
        }
    })
    httpc:set_keepalive(5000, 100)
    --httpc:close()
    return res, err_
end
